### ISSUE TITLE
Error in train 

### ISSUE THREAD

**Issue by L-ED** [zju3dv/NeuralRecon-W#11]
Hi, thank you for code! I created custom dataset from colmap workspace. After i changed train config file for my colmap workspace. After train launch i have this output:

scripts/train.sh first_ config/train.yaml 1 1
+ set -u
++ date +%Y%m%d_%H%M%S
+ now=20220721_210102
+ jobname=train-first_-20220721_210102
+ echo 'job name is train-first_-20220721_210102'
job name is train-first_-20220721_210102
+ config_file=config/train.yaml
+ mkdir -p log
+ mkdir -p logs/train-first_-20220721_210102
+ cp config/train.yaml logs/train-first_-20220721_210102
+ export CUDA_VISIBLE_DEVICES=0
+ CUDA_VISIBLE_DEVICES=0
+ python train.py --cfg_path config/train.yaml --num_gpus 1 --num_nodes 1 --num_epochs 20 --batch_size 2048 --test_batch_size 512 --num_workers 16 --exp_name train-first_-20220721_210102
+ tee log/train-first_-20220721_210102.log
INFO - 2022-07-21 21:01:04,525 - rasterization - Cannot import nvdiffrast
INFO - 2022-07-21 21:01:04,858 - seed - Global seed set to 66
INFO - 2022-07-21 21:01:04,906 - trainer - GPU available: True, used: True
INFO - 2022-07-21 21:01:04,906 - trainer - TPU available: False, using: 0 TPU cores
INFO - 2022-07-21 21:01:04,906 - trainer - IPU available: False, using: 0 IPUs
2022-07-21 21:01:04.907 | WARNING  | datasets.data:setup:51 - Default process group has not been initialized, please make sure to call init_process_group. (set world_size=1 and rank=0)
training octree will be in level: 9, with respect to voxel size 0.03987033383354102
Initializing data loaders...
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    main(hparams, config)
  File "train.py", line 64, in main
    trainer.fit(system, datamodule=data_module)
  File "/home/led/anaconda3/envs/NRW/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/home/led/anaconda3/envs/NRW/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/home/led/anaconda3/envs/NRW/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1168, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/led/anaconda3/envs/NRW/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/led/ML/3D_reconstruction/NeuralRecon-W/datasets/data.py", line 68, in setup
    self.train_dataset = self._setup_dataset(
  File "/home/led/ML/3D_reconstruction/NeuralRecon-W/datasets/data.py", line 104, in _setup_dataset
    splits_names = next(
StopIteration

**Comment by Burningdust21** [comment]
Hi, thanks for your interest in our work! 
It looks like the cache folder is missing, maybe some pre-processing procedures failed or skipped, could you post the structure of your working directory here?

**Comment by L-ED** [comment]
My working directory looks like this (cNR_w is virtual env)
.
├── assets
├── cNR_w
│   ├── bin
│   ├── etc
│   │   └── jupyter
│   ├── lib
│   │   └── python3.8
│   └── share
│       ├── applications
│       ├── doc
│       ├── icons
│       ├── jupyter
│       └── man
├── config
│   ├── deeplabv3_config
│   │   └── _base_
│   └── __pycache__
├── data
│   └── dataset1 -> /home/led/ML/data/dataset1
├── datasets
│   └── __pycache__
├── evaluations
├── lightning_modules
│   └── __pycache__
├── log
├── logs
│   ├── train-first-20220721_200622
│   ├── train-first-20220721_200648
│   ├── train-first-20220721_200828
│   ├── train-first-20220721_200832
│   ├── train-first-20220721_200921
│   ├── train-first-20220721_200925
│   ├── train-first-20220721_204615
│   ├── train-first-20220721_204744
│   ├── train-first-20220721_204826
│   ├── train-first-20220721_204915
│   ├── train-first-20220721_204924
│   ├── train-first-20220721_205606
│   ├── train-first-20220721_205630
│   ├── train-first-20220721_205650
│   └── train-first_-20220721_210102
├── models
│   └── __pycache__
├── __pycache__
├── rendering
│   └── __pycache__
├── scripts
├── tools
│   ├── prepare_data
│   │   └── __pycache__
│   └── __pycache__
├── utils
│   └── __pycache__
└── weights


Dataset directory structure is 
/home/led/ML/data/dataset1
├── 100_imgs_s
│   ├── dense
│   │   ├── images
│   │   ├── sparse
│   │   └── stereo
│   ├── images
│   ├── so_colmap
│   │   ├── colmap
│   │   ├── colmap_sparse
│   │   ├── colmap_text
│   │   └── dense
│   ├── sparse
│   └── stereo
│       ├── consistency_graphs
│       ├── depth_maps
│       └── normal_maps
├── 155_imgs_f
│   ├── dense
│   │   ├── images
│   │   ├── sparse
│   │   └── stereo
│   ├── images
│   └── sparse
│       └── 0
├── 350_imgs_f
│   ├── dense
│   │   ├── images
│   │   ├── sparse
│   │   └── stereo
│   ├── images
│   └── sparse
│       └── 0
└── recon_data
    └── 100_imgs_s
        └── split_0

**Comment by Burningdust21** [comment]
Hi, it seems you didn't follow our data preprocessing instructions on your own datasets. You can simply use [this script](https://github.com/zju3dv/NeuralRecon-W/blob/main/scripts/preprocess_data.sh) to process your data.
