### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by sunshinejuanjuan123** [zju3dv/NeuralRecon-W#34]
run
for SCENE_NAME in brandenburg_gate; do
  scripts/data_generation.sh /nas/datasets/Heritage-Recon/${SCENE_NAME}
done

python tools/prepare_data/prepare_data_cache.py --root_dir /nas/datasets/Heritage-Recon/brandenburg_gate --dataset_name phototourism --cache_dir cache_sgs --img_downscale 1 --semantic_map_path semantic_maps --split_to_chunks 64

[WARNING] batch has 0 intersections!!
[WARNING] batch has 0 intersections!!
[WARNING] batch has 0 intersections!!
Traceback (most recent call last):
  File "/nas/users/NeuralRecon-W/tools/prepare_data/prepare_data_cache.py", line 176, in <module>
    dataset = dataset_dict[args.dataset_name](**kwargs)
  File "/nas/users/NeuralRecon-W/./datasets/phototourism.py", line 123, in __init__
    self.read_meta()
  File "/nas/users/NeuralRecon-W/./datasets/phototourism.py", line 667, in read_meta
    curent_percent = valid_num / current_len
ZeroDivisionError: division by zero

> /nas/users/NeuralRecon-W/datasets/phototourism.py(667)read_meta()
    666                         current_len = rays.size()[0]
--> 667                         curent_percent = valid_num / current_len
    668                         padding_length = int(np.ceil((self.depth_percent * current_len - valid_num) / (1 - self.depth_percent)))

ipdb> current_len
0
for id_ in tqdm(img_ids_split):
ipdb> id_
15

**Comment by czg-first** [comment]
I also meet this problem.

**Comment by Dugabom** [comment]
have you solved this yet?
