### ISSUE TITLE
Image downsizing results in runtime error RuntimeError: Trying to create tensor with negative dimension -18: [-18]

### ISSUE THREAD

**Issue by BarnitaSharma** [zju3dv/NeuralRecon-W#36]
Preparing cache for scale 4...
reading sfm result from ../neuralsfm...
Note: training near far will generate from sparse voxel!!!!
Reading images.bin..
Reading cameras.bin..
Compute c2w poses..
Generating rays and rgbs..
100%|██████████| 778613/778613 [00:06<00:00, 116915.10it/s]
2022-12-30 16:36:11.097 | DEBUG    | tools.prepare_data.generate_voxel:gen_octree_from_sfm:59 - Points filtered from raw point cloud: 27595/100040
2022-12-30 16:36:11.753 | DEBUG    | tools.prepare_data.generate_voxel:gen_octree:124 - number of points for voxel generation: 725832/744660
2022-12-30 16:36:13.536 | DEBUG    | tools.prepare_data.generate_voxel:gen_octree:147 - level: 5 for expected voxel size: 0.25
2022-12-30 16:36:15.178 | DEBUG    | tools.prepare_data.generate_voxel:gen_octree_from_sfm:59 - Points filtered from raw point cloud: 27595/100040
2022-12-30 16:36:35.314 | DEBUG    | tools.prepare_data.generate_voxel:gen_octree:124 - number of points for voxel generation: 3862151/3893596
2022-12-30 16:36:35.339 | DEBUG    | tools.prepare_data.generate_voxel:gen_octree:147 - level: 5 for expected voxel size: 0.25
Mean Projection Error: tensor(1.0761)
100%|██████████| 1/1 [00:00<00:00, 32.90it/s]
100%|██████████| 1/1 [00:00<00:00, 35.89it/s]
  0%|          | 0/1353 [00:00<?, ?it/s]
padding valid depth percentage: from 0.20059621871812974 to 0.2 with padding -18
Traceback (most recent call last):
  File "tools/prepare_data/prepare_data_cache.py", line 176, in <module>
    dataset = dataset_dict[args.dataset_name](**kwargs)
  File "/home/imlab/neural3d/NeuralRecon-W/./datasets/phototourism.py", line 122, in __init__
    self.read_meta()
  File "/home/imlab/neural3d/NeuralRecon-W/./datasets/phototourism.py", line 666, in read_meta
    pad_ind =  torch.floor((torch.rand(padding_length) * valid_num)).long()
RuntimeError: Trying to create tensor with negative dimension -18: [-18]

**Comment by lt-xiang** [comment]
Hi have you solved it ?
