### ISSUE TITLE
Instalation error

### ISSUE THREAD

**Issue by PBazaluk** [zju3dv/NeuralRecon-W#55]
Hello I'm facing an error when trying to do the ```pip install -r requirements.txt```  it is something with the compilation process of mmcv but I con't find the code that failed to compile, it's problaby some configuration problem or some lib or include that is missing but I don't know what that is missing, so can someone help me describing what can be the problem?

Error code:
```
[33/129] c++ -MMD -MF /tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/build/temp.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/cpu/voxelization.o.d -pthread -B /home/pedro/miniconda3/envs/neuconw/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/mmcv/ops/csrc/pytorch -I/tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/mmcv/ops/csrc/common -I/tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/mmcv/ops/csrc/common/cuda -I/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/include -I/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/include/TH -I/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/include/THC -I/home/pedro/miniconda3/envs/neuconw/include -I/home/pedro/miniconda3/envs/neuconw/include/python3.8 -c -c /tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/mmcv/ops/csrc/pytorch/cpu/voxelization.cpp -o /tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/build/temp.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/cpu/voxelization.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
      cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
          subprocess.run(
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tgq44dzg/mmcv-full_abd2097bc38d44d187e1a2007282d957/setup.py", line 543, in <module>
          setup(
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
          build_ext.build_extensions(self)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/pedro/miniconda3/envs/neuconw/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects
```

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
